### ISSUE TITLE
a simple react example would be so nice

### ISSUE THREAD

**Issue by ajoslin103** [activejs/activejs#3]
a simple react example would be so nice

**Comment by dabalyan** [comment]
hey @ajoslin103 thanks for opening the issue.

I updated the docs with more examples, please take a took and let me know if you would like to see something specific.
Here are the updated relevant docs links:

- [Counter with React+ActiveJS](https://docs.activejs.dev/integrations/react)
- [Custom useUnit Hook](https://docs.activejs.dev/integrations/react/useunit-hook)
- [Custom useObservable Hook](https://docs.activejs.dev/integrations/react/useobservable-hook)
- [AsyncSystem+React](https://docs.activejs.dev/fundamentals/systems/asyncsystem#react)

**Comment by ajoslin103** [comment]
These are great ! Just what I was looking for !

I'm going to try to hook up an Ably listener to the Async system -- I'd like messages from the remote system to modify my state 

Thanks!

**Comment by dabalyan** [comment]
@ajoslin103 best of luck 👍

**Comment by ajoslin103** [comment]
thanks!  

is there any reason not to combine units into more complex state handlers?

in this case I wish to combine a 3-state with a boolean

I could have exposed roleChosen as a function to check if roleChoice !== ROLE_NOT_CHOSEN 

I have struggled with state over the years and am coming to ActiveJS to learn again from the ground up

I will get to the ActiveSync in good time - but I want to feel my way to it and thereby have a deeper understanding

```
// https://docs.activejs.dev/fundamentals/units
import { StringUnit } from "@activejs/core";
import { BoolUnit } from "@activejs/core";

const BUSINESS_ROLE = `business`;
const CONSUMER_ROLE = `consumer`;
const ROLE_NOT_CHOSEN = `no choice`;

export const roleChoice = new StringUnit({
    initialValue: ROLE_NOT_CHOSEN
});

export const roleChosen = new BoolUnit({
    initialValue: false
});

// define pure functions to dispatch
export const business = () => {
    roleChosen.dispatch(true);
    return BUSINESS_ROLE
};
export const consumer = () => {
    roleChosen.dispatch(true);
    return CONSUMER_ROLE
};
```

**Comment by ajoslin103** [comment]
and 

```
// https://docs.activejs.dev/fundamentals/units
import { BoolUnit } from "@activejs/core";
import { NumUnit } from "@activejs/core";
import { StringUnit } from "@activejs/core";

// this state tracks whether the demo can be started
// 
// based upon these sub-states:
//  a messaging connection is established
//  a remote appKey is known
//  a demo code is shared

export const canStartdDemo = new BoolUnit({
    initialValue: false
});

export const messagingConnected = new BoolUnit({
    initialValue: false
});

export const remoteAppKey = new StringUnit({
    initialValue: ''
});

export const sharedDemoCode = new NumUnit({
    initialValue: 0
});

const attemptStartDemo = () => {
    if (messagingConnectionEstablished &&
        sharedDemoCode && remoteAppKey) {
        canStartdDemo.dispatch(true);
    }
}

export const saveRemoteAppKey = (newKey) => {
    remoteAppKey.dispatch(newKey);
    attemptStartDemo();
}

export const saveDemoCode = (newCode) => {
    sharedDemoCode.dispatch(newCode);
    attemptStartDemo();
}

export const messagingConnectionEstablished = () => {
    messagingConnected.dispatch(true);
    attemptStartDemo();
}
```

**Comment by ajoslin103** [comment]
next up would be to subscribe to the "super-states" that are driven by their sub-states

at least that's the plan !!

gang aft agley !!

**Comment by dabalyan** [comment]
Regarding this:

> ```
> // https://docs.activejs.dev/fundamentals/units
> import { StringUnit } from "@activejs/core";
> import { BoolUnit } from "@activejs/core";
> 
> const BUSINESS_ROLE = `business`;
> const CONSUMER_ROLE = `consumer`;
> const ROLE_NOT_CHOSEN = `no choice`;
> 
> export const roleChoice = new StringUnit({
>     initialValue: ROLE_NOT_CHOSEN
> });
> 
> export const roleChosen = new BoolUnit({
>     initialValue: false
> });
> 
> // define pure functions to dispatch
> export const business = () => {
>     roleChosen.dispatch(true);
>     return BUSINESS_ROLE
> };
> export const consumer = () => {
>     roleChosen.dispatch(true);
>     return CONSUMER_ROLE
> };
> ```

Since ActiveJS is a built to be reactive, and is based on RxJS, you can derive states by using RxJS pipes. In this case I'd probably do something like this:

```ts
// https://docs.activejs.dev/fundamentals/units
import { StringUnit, BoolUnit } from "@activejs/core";
import { map, shareReplay } from "rxjs/operators";

const BUSINESS_ROLE = `business`;
const CONSUMER_ROLE = `consumer`;
const ROLE_NOT_CHOSEN = `no choice`;

export const roleChoice = new StringUnit({
    initialValue: ROLE_NOT_CHOSEN
});

// create an Observable of derived value
export const roleChosen = roleChoice.pipe(
   map(role => role !== ROLE_NOT_CHOSEN), // derive a new state by mapping the value to a condition
   shareReplay(1) // makes it more performant, all observers share the same computed value
)

// and then, dispatch the new roles directly, because pure functions are only useful if
// you're producing a new value based on previous value
// so, 
roleChoice.dispatch(BUSINESS_ROLE); // or dispatch any other role
```

> I have struggled with state over the years and am coming to ActiveJS to learn again from the ground up
I will get to the ActiveSync in good time - but I want to feel my way to it and thereby have a deeper understanding

Just keep it up, it'll come to you surely :)

**Comment by dabalyan** [comment]
And I'd suggest the same approach for any other derived state, embrace RxJS pipe, and your derived state will stay up to date no matter from where and when you update it.

Also, at first I didn't get the "gang aft agley !!", but quick google search tells me that I connect with it on a spiritual level 😄
